# Generated by Django 6.0 on 2025-12-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='contributor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
